import { defineConfig, devices } from '@playwright/test';
import { existsSync } from 'fs';
import { resolve } from 'path';

const CI = !!process.env.CI;
const includeAllBrowsers = CI || process.env.PLAYWRIGHT_ALL_BROWSERS === 'true';

// Use HTTPS only when certs already exist (generated by running the client once).
// On first run, or in CI, fall back to HTTP — the server does the same.
const certsExist =
  !CI &&
  existsSync(resolve(__dirname, 'certs/localhost-key.pem')) &&
  existsSync(resolve(__dirname, 'certs/localhost.pem'));

const protocol = certsExist ? 'https' : 'http';
const clientUrl = `${protocol}://localhost:5173`;
const serverHealthUrl = `${protocol}://localhost:3001/api/health`;

export default defineConfig({
  testDir: './client/tests',
  fullyParallel: false,
  forbidOnly: CI,
  retries: CI ? 2 : 0,
  workers: 1,
  reporter: [['html', { outputFolder: 'client/playwright-report' }]],
  use: {
    baseURL: clientUrl,
    trace: 'on-first-retry',
    // Accept self-signed mkcert certificates in local dev.
    ignoreHTTPSErrors: true,
    // Disable framer-motion (and other CSS) animations so elements are immediately
    // stable for Playwright's actionability checks, especially on webkit.
    reducedMotion: 'reduce',
  },

  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    ...(includeAllBrowsers
      ? [
          {
            name: 'firefox',
            use: { ...devices['Desktop Firefox'] },
          },
          {
            name: 'webkit',
            use: { ...devices['Desktop Safari'] },
          },
        ]
      : []),
  ],

  // Start both the backend server and the Vite client before running tests.
  // The server's cross-platform `start` script (ts-node) is used instead of
  // `dev` to avoid the Windows-only kill-port step.
  webServer: [
    {
      command: 'npm run start --prefix server',
      url: serverHealthUrl,
      reuseExistingServer: !CI,
      timeout: 120_000,
    },
    {
      command: 'npm run dev --prefix client',
      url: clientUrl,
      reuseExistingServer: !CI,
      env: { SKIP_MKCERT: 'true' },
      timeout: 120_000,
    },
  ],
});
